modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="modexonia"
version="1.0.0"
displayName="mod exonia"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="mador, MCreator"

[[dependencies.modexonia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




